### ISSUE TITLE
DatabaseError on CentOS 7

### ISSUE THREAD

**Issue by benh57** [ceph/calamari#422]
calamari 1.4 branch (1.4.0rc7), built latest
romana 1.2.2 (head)

Made modification to gevent/greenlet version per https://github.com/ceph/calamari/issues/406 so that it will compile on C7

I now get this when hitting the main page:

[Fri Apr 15 20:02:10.991473 2016] [:error] [pid 21468] [remote 10.30.8.48:184] mod_wsgi (pid=21468): Exception occurred processing WSGI script '/opt/calamari/conf/calamari.wsgi'.
[Fri Apr 15 20:02:10.991527 2016] [:error] [pid 21468] [remote 10.30.8.48:184] Traceback (most recent call last):
[Fri Apr 15 20:02:10.991553 2016] [:error] [pid 21468] [remote 10.30.8.48:184]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/http/response.py", line 236, in close
[Fri Apr 15 20:02:10.991587 2016] [:error] [pid 21468] [remote 10.30.8.48:184]     signals.request_finished.send(sender=self._handler_class)
[Fri Apr 15 20:02:10.991611 2016] [:error] [pid 21468] [remote 10.30.8.48:184]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
[Fri Apr 15 20:02:10.991641 2016] [:error] [pid 21468] [remote 10.30.8.48:184]     response = receiver(signal=self, sender=sender, **named)
[Fri Apr 15 20:02:10.991658 2016] [:error] [pid 21468] [remote 10.30.8.48:184]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/__init__.py", line 52, in close_connection
[Fri Apr 15 20:02:10.991682 2016] [:error] [pid 21468] [remote 10.30.8.48:184]     connections[conn].close()
[Fri Apr 15 20:02:10.991697 2016] [:error] [pid 21468] [remote 10.30.8.48:184]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 136, in close
[Fri Apr 15 20:02:10.991722 2016] [:error] [pid 21468] [remote 10.30.8.48:184]     self.validate_thread_sharing()
[Fri Apr 15 20:02:10.991737 2016] [:error] [pid 21468] [remote 10.30.8.48:184]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 154, in validate_thread_sharing
[Fri Apr 15 20:02:10.991760 2016] [:error] [pid 21468] [remote 10.30.8.48:184]     % (self.alias, self._thread_ident, thread.get_ident()))
[Fri Apr 15 20:02:10.991781 2016] [:error] [pid 21468] [remote 10.30.8.48:184] DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 139821530552064 and this is thread id 139821782708048.

18:05:12 root@sm-calamari /opt/calamari/conf $ supervisorctl status
calamari-lite                    RUNNING   pid 5686, uptime 0:20:15

**Comment by GregMeno** [comment]
@benh57 fixed in v1.4.0-rc10

**Comment by chengweiv5** [comment]
I'm just installed the latest calamari-server 1.4.8 and meet this issue, is this a regression?

**Comment by chengweiv5** [comment]
I just built v1.4.0-rc10 and the error still here like below

```
[Fri Aug 05 06:57:07.436575 2016] [:error] [pid 13709] [remote 10.1.241.55:116]     signals.request_finished.send(sender=self._handler_class)
[Fri Aug 05 06:57:07.436592 2016] [:error] [pid 13709] [remote 10.1.241.55:116]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
[Fri Aug 05 06:57:07.436670 2016] [:error] [pid 13709] [remote 10.1.241.55:116]     response = receiver(signal=self, sender=sender, **named)
[Fri Aug 05 06:57:07.436680 2016] [:error] [pid 13709] [remote 10.1.241.55:116]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/__init__.py", line 52, in close_connection
[Fri Aug 05 06:57:07.436725 2016] [:error] [pid 13709] [remote 10.1.241.55:116]     connections[conn].close()
[Fri Aug 05 06:57:07.436734 2016] [:error] [pid 13709] [remote 10.1.241.55:116]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 136, in close
[Fri Aug 05 06:57:07.436803 2016] [:error] [pid 13709] [remote 10.1.241.55:116]     self.validate_thread_sharing()
[Fri Aug 05 06:57:07.436810 2016] [:error] [pid 13709] [remote 10.1.241.55:116]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 154, in validate_thread_sharing
[Fri Aug 05 06:57:07.436822 2016] [:error] [pid 13709] [remote 10.1.241.55:116]     % (self.alias, self._thread_ident, thread.get_ident()))
[Fri Aug 05 06:57:07.436834 2016] [:error] [pid 13709] [remote 10.1.241.55:116] DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140207070574336 and this is thread id 140207323787824.
```

even I did `calamari-ctl clear --yes-i-am-sure`, nothing changed.

**Comment by wzyuliyang** [comment]
i meet the same error
```
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 139974111680256 and this is thread id 139974363259280.
```
with 
* calamari-clients-1.3.1.1-0.el7.centos.x86_64
* calamari-server-1.4.8-0.el7.centos.x86_64

**Comment by laggeduout** [comment]
I am also hitting this with calamari-server-1.4.8-0.el7.centos.x86_64 - is there a good work around?

**Comment by laggeduout** [comment]
This commit seems to stop the warnings https://github.com/ceph/calamari/commit/044791672cb63123b54a2caa7d6e7824ef494655

**Comment by chengweiv5** [comment]
I found a good calamari alternative https://github.com/inkscope/inkscope
